sc: scientia
cfg: config
cfg_edit: edit
cfg_init: init
cfg_read: read
add: add
edit: edit
edit_id: id
edit_list: list

sc -> cfg
cfg -> cfg_init
cfg -> cfg_edit
cfg -> cfg_read

sc -> add

sc -> edit
edit -> edit_id
edit -> edit_list
